version: "3.7"

services:
  customer-registration:
    image: axonbank/customer-registration:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-bank

networks:
  axon-bank:
    external: true
