management:
  endpoints:
    web:
      exposure:
        include: "*"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    keep-alive-timeout: 30000
    keep-alive-time: 5000
    heartbeat:
      enabled: true

---
spring:
  profiles: dev

logging:
  level:
    root: info
    com.karamelsoft: trace

---
spring:
  profiles: swarm

axon:
  axonserver:
    servers: axonserver


