version: "3.7"

services:
  payment-processor:
    image: axonbank/payment-processor:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-bank

networks:
  axon-bank:
    external: true
