version: "3.7"

services:
  cards-command:
    image: axonbank/cards-command:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-bank

networks:
  axon-bank:
    external: true
