version: "3.7"

services:
  accounts-command:
    image: axonbank/accounts-command:latest
    environment:
      SPRING_PROFILES_ACTIVE: swarm
    networks:
      - axon-bank

networks:
  axon-bank:
    external: true
